name: 'avi'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github_token:
    description: The GITHUB_TOKEN secret
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
